version: '3.1'
services:
  nextjs:
    #image: "nextjs-boilerplate:latest"
    build:
      context: .
      target: nextjs
      args:
        BUILD_TYPE: prod
        #BUILD_TYPE: dev
        NODE_VERSION: lts
        #NODE_VERSION: current
    restart: always
    ports:
      - 9000:9000
