---
name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '41 14 * * 5'

jobs:
  build:
    name: Lubt
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CSS: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_ES: true
